import type { ReminderCategory } from '../reminders/types';

type Range = 'day' | 'week' | 'month';
type Props = { categories: ReminderCategory[]; range: Range; adherence: number; digest: { good: string; work: string }; kpis: Array<{ label: string; value: string; sub: string; graphic?: string }>; waterSeries: number[]; waterGoal: number; onRangeChange: (range: Range) => void };

export default function StatisticsPage({ range, adherence, digest, kpis, waterSeries, waterGoal, onRangeChange }: Props) {
  const labels = range === 'day' ? ['today'] : range === 'week' ? ['S', 'M', 'T', 'W', 'T', 'F', 'S'] : waterSeries.map((_, index) => index % 5 === 0 ? String(index + 1) : '');
  const maximum = Math.max(...waterSeries, waterGoal, 1);
  return <section id="page-stats"><div className="ptitle">Statistics</div><p className="psub">How well the day's reminders are being acted on. Each ring is a category — the coloured sweep is how much of it you've completed.</p><div className="seg-ctl" id="rangeCtl">{(['day', 'week', 'month'] as const).map((item) => <button key={item} type="button" aria-pressed={range === item} data-r={item} onClick={() => onRangeChange(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div><div className="statgrid"><div className="card" style={{ textAlign: 'center' }}><h2 style={{ textAlign: 'left' }}>Adherence</h2><svg className="rings" id="ringChart" viewBox="0 0 300 300"><circle className="rtrack" cx="150" cy="150" r="110" strokeWidth="12" /><circle className="rval" cx="150" cy="150" r="110" stroke="var(--teal)" strokeWidth="12" strokeDasharray={`${adherence * 6.91} 691`} transform="rotate(-90 150 150)" /><text x="150" y="146" textAnchor="middle" style={{ font: '800 30px Syne', fill: 'var(--ink)' }}>{adherence}%</text><text x="150" y="166" textAnchor="middle" style={{ fill: 'var(--muted)', font: '500 10px DM Sans', letterSpacing: '.1em' }}>ADHERENCE</text></svg><div className="digest"><div className="ln good"><span className="ic">✓</span><span dangerouslySetInnerHTML={{ __html: digest.good }} /></div><div className="ln work"><span className="ic">!</span><span dangerouslySetInnerHTML={{ __html: digest.work }} /></div></div></div><div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><div className="card"><h2>Overview <span className="r">{range === 'day' ? 'today' : range === 'week' ? 'last 7 days' : 'last 30 days'}</span></h2><div className="kpi">{kpis.map((kpi) => <div className="k" key={kpi.label}><div className="gfx">{kpi.graphic || '◌'}</div><div className="txt"><p>{kpi.label}</p><b>{kpi.value}</b><small className="sub">{kpi.sub}</small></div></div>)}</div></div><div className="card"><h2>Water trend <span className="r">days at or above goal in blue</span></h2><div className="bars">{waterSeries.map((value, index) => <div className={`b ${value >= waterGoal ? 'hi' : ''}`} key={index}><i style={{ height: `${8 + value / maximum * 88}px` }} title={`${value} ml`} /></div>)}</div><div className="xlab">{labels.map((label, index) => <span key={index}>{label}</span>)}</div></div></div></div></section>;
}
